version: '3.7'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: my_secure_password
    ports:
      - "8123:8123"    # HTTP interface
      - "9000:9000"    # Native TCP interface (used by Python clients, CLI)
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_config/config.xml:/etc/clickhouse-server/config.d/memory.xml:ro

volumes:
  clickhouse_data: